CREATE TABLE Country(
	ID INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(255) NOT NULL UNIQUE
)

CREATE TABLE [State](
	ID INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(255) NOT NULL,
	CountryID INT,
	FOREIGN KEY (CountryID) REFERENCES Country(ID)
)

CREATE TABLE City(
	ID INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(255) NOT NULL,
	CountryID INT,
	StateID INT,
	FOREIGN KEY (CountryID) REFERENCES Country(ID),
	FOREIGN KEY (StateID) REFERENCES [State](ID)
)

CREATE TABLE [User](
	ID INT PRIMARY KEY IDENTITY(1,1),
	Username NVARCHAR(255) NOT NULL UNIQUE,
	Email NVARCHAR(255) NOT NULL UNIQUE,
	CountryID INT,
	[StateID] INT,
	CityID INT,
	FOREIGN KEY (CountryID) REFERENCES Country(ID),
	FOREIGN KEY (StateID) REFERENCES [State](ID),
	FOREIGN KEY (CityID) REFERENCES City(ID)
)